#%RAML 1.0 NamedExample

  {
        "customerName": "Giri",   
        "customerId": "SW0127841111",
        "phoneNumber": 122323134,
        "address": {
            "houseNo": "6-2-304",
            "street": "bckhsabcsvc",
            "city": "newyork",
            "country": "newyork",
            "zip": "07008"
        }
    }